language: python
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 GOOGLE_APP_ENGINE=${HOME}/google-cloud-sdk/platform/google_appengine
before_install:
# If the SDK is not already cached, download it and unpack it
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
# [START auth]
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_a6904816add3_key -iv $encrypted_a6904816add3_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file client-secret.json
# [END auth]
install:
# Set the correct project to deploy to
- gcloud config set project marketo-1041
- gcloud components update app-engine-python
# Install the Python dependencies
- pip install -r requirements.txt -t lib/
script:
# Run the unit tests
- python -m tests.test_sync
# [START deploy]
# Deploy the app
- gcloud app deploy app.yaml worker.yaml queue.yaml
# [END deploy]
