runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /datadog
  script: gae_datadog.application
- url: /.*
  script: sync_app.application

skip_files:
- ^instance/*